[package]
name = "maanantairastit-client"
version = "0.1.0"
description = "Maanantairastien EMIT 250 -lukijaclient"
edition = "2021"
rust-version = "1.88"

[lib]
name = "maanantairastit_client_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = [] }
serde = { version = "1.0.229", features = ["derive"] }
serialport = "4.10.0"
rusqlite = { version = "0.38.0", features = ["bundled"] }
